---
format_version: 1
pipelines:
  ci-workshop: # pipeline name
    group: ci_workshop # pipeline group
    label_template: '${mygit[:8]}'
    lock_behavior: none
    materials:
      ci-workshop:
        git: 'git@github.com:minnn-tw/ci-workshop.git'
        branch: master
    stages:
      - Echo-Hello-World:
          clean_workspace: true
          jobs:
            hello-world:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - hello-world
